// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: hashtag.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HashtagService_SearchByHashtag_FullMethodName     = "/hashtag.HashtagService/SearchByHashtag"
	HashtagService_GetTrendingHashtags_FullMethodName = "/hashtag.HashtagService/GetTrendingHashtags"
	HashtagService_AddHashtagsToPost_FullMethodName   = "/hashtag.HashtagService/AddHashtagsToPost"
)

// HashtagServiceClient is the client API for HashtagService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HashtagServiceClient interface {
	// --- User-facing RPCs ---
	// Search for posts by a specific hashtag
	SearchByHashtag(ctx context.Context, in *SearchByHashtagRequest, opts ...grpc.CallOption) (*SearchByHashtagResponse, error)
	// Get a list of trending hashtags
	GetTrendingHashtags(ctx context.Context, in *GetTrendingHashtagsRequest, opts ...grpc.CallOption) (*GetTrendingHashtagsResponse, error)
	// --- Internal RPC (called by worker-service) ---
	AddHashtagsToPost(ctx context.Context, in *AddHashtagsToPostRequest, opts ...grpc.CallOption) (*AddHashtagsToPostResponse, error)
}

type hashtagServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHashtagServiceClient(cc grpc.ClientConnInterface) HashtagServiceClient {
	return &hashtagServiceClient{cc}
}

func (c *hashtagServiceClient) SearchByHashtag(ctx context.Context, in *SearchByHashtagRequest, opts ...grpc.CallOption) (*SearchByHashtagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchByHashtagResponse)
	err := c.cc.Invoke(ctx, HashtagService_SearchByHashtag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hashtagServiceClient) GetTrendingHashtags(ctx context.Context, in *GetTrendingHashtagsRequest, opts ...grpc.CallOption) (*GetTrendingHashtagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTrendingHashtagsResponse)
	err := c.cc.Invoke(ctx, HashtagService_GetTrendingHashtags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hashtagServiceClient) AddHashtagsToPost(ctx context.Context, in *AddHashtagsToPostRequest, opts ...grpc.CallOption) (*AddHashtagsToPostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddHashtagsToPostResponse)
	err := c.cc.Invoke(ctx, HashtagService_AddHashtagsToPost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HashtagServiceServer is the server API for HashtagService service.
// All implementations must embed UnimplementedHashtagServiceServer
// for forward compatibility.
type HashtagServiceServer interface {
	// --- User-facing RPCs ---
	// Search for posts by a specific hashtag
	SearchByHashtag(context.Context, *SearchByHashtagRequest) (*SearchByHashtagResponse, error)
	// Get a list of trending hashtags
	GetTrendingHashtags(context.Context, *GetTrendingHashtagsRequest) (*GetTrendingHashtagsResponse, error)
	// --- Internal RPC (called by worker-service) ---
	AddHashtagsToPost(context.Context, *AddHashtagsToPostRequest) (*AddHashtagsToPostResponse, error)
	mustEmbedUnimplementedHashtagServiceServer()
}

// UnimplementedHashtagServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHashtagServiceServer struct{}

func (UnimplementedHashtagServiceServer) SearchByHashtag(context.Context, *SearchByHashtagRequest) (*SearchByHashtagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchByHashtag not implemented")
}
func (UnimplementedHashtagServiceServer) GetTrendingHashtags(context.Context, *GetTrendingHashtagsRequest) (*GetTrendingHashtagsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrendingHashtags not implemented")
}
func (UnimplementedHashtagServiceServer) AddHashtagsToPost(context.Context, *AddHashtagsToPostRequest) (*AddHashtagsToPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddHashtagsToPost not implemented")
}
func (UnimplementedHashtagServiceServer) mustEmbedUnimplementedHashtagServiceServer() {}
func (UnimplementedHashtagServiceServer) testEmbeddedByValue()                        {}

// UnsafeHashtagServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HashtagServiceServer will
// result in compilation errors.
type UnsafeHashtagServiceServer interface {
	mustEmbedUnimplementedHashtagServiceServer()
}

func RegisterHashtagServiceServer(s grpc.ServiceRegistrar, srv HashtagServiceServer) {
	// If the following call pancis, it indicates UnimplementedHashtagServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HashtagService_ServiceDesc, srv)
}

func _HashtagService_SearchByHashtag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchByHashtagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashtagServiceServer).SearchByHashtag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HashtagService_SearchByHashtag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashtagServiceServer).SearchByHashtag(ctx, req.(*SearchByHashtagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HashtagService_GetTrendingHashtags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrendingHashtagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashtagServiceServer).GetTrendingHashtags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HashtagService_GetTrendingHashtags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashtagServiceServer).GetTrendingHashtags(ctx, req.(*GetTrendingHashtagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HashtagService_AddHashtagsToPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddHashtagsToPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashtagServiceServer).AddHashtagsToPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HashtagService_AddHashtagsToPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashtagServiceServer).AddHashtagsToPost(ctx, req.(*AddHashtagsToPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HashtagService_ServiceDesc is the grpc.ServiceDesc for HashtagService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HashtagService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hashtag.HashtagService",
	HandlerType: (*HashtagServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchByHashtag",
			Handler:    _HashtagService_SearchByHashtag_Handler,
		},
		{
			MethodName: "GetTrendingHashtags",
			Handler:    _HashtagService_GetTrendingHashtags_Handler,
		},
		{
			MethodName: "AddHashtagsToPost",
			Handler:    _HashtagService_AddHashtagsToPost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hashtag.proto",
}
