// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: user.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- Register ---
type RegisterUserRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Username    string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email       string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password    string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	DateOfBirth string                 `protobuf:"bytes,5,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Gender      string                 `protobuf:"bytes,6,opt,name=gender,proto3" json:"gender,omitempty"`
	// string profile_picture_url = 7; // REMOVED
	// string otp_code = 8; // REMOVED
	ConfirmPassword string `protobuf:"bytes,9,opt,name=confirm_password,json=confirmPassword,proto3" json:"confirm_password,omitempty"` // ADDED
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterUserRequest) Reset() {
	*x = RegisterUserRequest{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRequest) ProtoMessage() {}

func (x *RegisterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterUserRequest) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *RegisterUserRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *RegisterUserRequest) GetConfirmPassword() string {
	if x != nil {
		return x.ConfirmPassword
	}
	return ""
}

type RegisterUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // Return the new User ID
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"` // e.g., "Registration successful. Please check email."
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserResponse) Reset() {
	*x = RegisterUserResponse{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserResponse) ProtoMessage() {}

func (x *RegisterUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserResponse.ProtoReflect.Descriptor instead.
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterUserResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RegisterUserResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterUserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// --- Send OTP ---
type SendOtpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendOtpRequest) Reset() {
	*x = SendOtpRequest{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendOtpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOtpRequest) ProtoMessage() {}

func (x *SendOtpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOtpRequest.ProtoReflect.Descriptor instead.
func (*SendOtpRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *SendOtpRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type SendOtpResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Message          string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	RateLimitSeconds int32                  `protobuf:"varint,2,opt,name=rate_limit_seconds,json=rateLimitSeconds,proto3" json:"rate_limit_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SendOtpResponse) Reset() {
	*x = SendOtpResponse{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendOtpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOtpResponse) ProtoMessage() {}

func (x *SendOtpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOtpResponse.ProtoReflect.Descriptor instead.
func (*SendOtpResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *SendOtpResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendOtpResponse) GetRateLimitSeconds() int32 {
	if x != nil {
		return x.RateLimitSeconds
	}
	return 0
}

type HandleGoogleAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthCode      string                 `protobuf:"bytes,1,opt,name=auth_code,json=authCode,proto3" json:"auth_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleGoogleAuthRequest) Reset() {
	*x = HandleGoogleAuthRequest{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleGoogleAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleGoogleAuthRequest) ProtoMessage() {}

func (x *HandleGoogleAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleGoogleAuthRequest.ProtoReflect.Descriptor instead.
func (*HandleGoogleAuthRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *HandleGoogleAuthRequest) GetAuthCode() string {
	if x != nil {
		return x.AuthCode
	}
	return ""
}

// --- NEW: Verify Registration OTP ---
type VerifyRegistrationOtpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	OtpCode       string                 `protobuf:"bytes,2,opt,name=otp_code,json=otpCode,proto3" json:"otp_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRegistrationOtpRequest) Reset() {
	*x = VerifyRegistrationOtpRequest{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRegistrationOtpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRegistrationOtpRequest) ProtoMessage() {}

func (x *VerifyRegistrationOtpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRegistrationOtpRequest.ProtoReflect.Descriptor instead.
func (*VerifyRegistrationOtpRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *VerifyRegistrationOtpRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *VerifyRegistrationOtpRequest) GetOtpCode() string {
	if x != nil {
		return x.OtpCode
	}
	return ""
}

// Returns tokens, officially "logging in" the new user
type VerifyRegistrationOtpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRegistrationOtpResponse) Reset() {
	*x = VerifyRegistrationOtpResponse{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRegistrationOtpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRegistrationOtpResponse) ProtoMessage() {}

func (x *VerifyRegistrationOtpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRegistrationOtpResponse.ProtoReflect.Descriptor instead.
func (*VerifyRegistrationOtpResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *VerifyRegistrationOtpResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *VerifyRegistrationOtpResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// --- Login ---
type LoginRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EmailOrUsername string                 `protobuf:"bytes,1,opt,name=email_or_username,json=emailOrUsername,proto3" json:"email_or_username,omitempty"`
	Password        string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *LoginRequest) GetEmailOrUsername() string {
	if x != nil {
		return x.EmailOrUsername
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Message        string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	AccessToken    string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken   string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Is_2FaRequired bool                   `protobuf:"varint,4,opt,name=is_2fa_required,json=is2faRequired,proto3" json:"is_2fa_required,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *LoginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResponse) GetIs_2FaRequired() bool {
	if x != nil {
		return x.Is_2FaRequired
	}
	return false
}

// --- 2FA Verification ---
type Verify2FARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	OtpCode       string                 `protobuf:"bytes,2,opt,name=otp_code,json=otpCode,proto3" json:"otp_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Verify2FARequest) Reset() {
	*x = Verify2FARequest{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Verify2FARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Verify2FARequest) ProtoMessage() {}

func (x *Verify2FARequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Verify2FARequest.ProtoReflect.Descriptor instead.
func (*Verify2FARequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *Verify2FARequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Verify2FARequest) GetOtpCode() string {
	if x != nil {
		return x.OtpCode
	}
	return ""
}

type Verify2FAResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Verify2FAResponse) Reset() {
	*x = Verify2FAResponse{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Verify2FAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Verify2FAResponse) ProtoMessage() {}

func (x *Verify2FAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Verify2FAResponse.ProtoReflect.Descriptor instead.
func (*Verify2FAResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *Verify2FAResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *Verify2FAResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// --- Password Reset (Request) ---
type SendPasswordResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPasswordResetRequest) Reset() {
	*x = SendPasswordResetRequest{}
	mi := &file_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPasswordResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPasswordResetRequest) ProtoMessage() {}

func (x *SendPasswordResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPasswordResetRequest.ProtoReflect.Descriptor instead.
func (*SendPasswordResetRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

func (x *SendPasswordResetRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type SendPasswordResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPasswordResetResponse) Reset() {
	*x = SendPasswordResetResponse{}
	mi := &file_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPasswordResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPasswordResetResponse) ProtoMessage() {}

func (x *SendPasswordResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPasswordResetResponse.ProtoReflect.Descriptor instead.
func (*SendPasswordResetResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{12}
}

func (x *SendPasswordResetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// --- Password Reset (Submit) ---
type ResetPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	OtpCode       string                 `protobuf:"bytes,2,opt,name=otp_code,json=otpCode,proto3" json:"otp_code,omitempty"`
	NewPassword   string                 `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordRequest) Reset() {
	*x = ResetPasswordRequest{}
	mi := &file_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordRequest) ProtoMessage() {}

func (x *ResetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordRequest.ProtoReflect.Descriptor instead.
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{13}
}

func (x *ResetPasswordRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ResetPasswordRequest) GetOtpCode() string {
	if x != nil {
		return x.OtpCode
	}
	return ""
}

func (x *ResetPasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type ResetPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordResponse) Reset() {
	*x = ResetPasswordResponse{}
	mi := &file_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordResponse) ProtoMessage() {}

func (x *ResetPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordResponse.ProtoReflect.Descriptor instead.
func (*ResetPasswordResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{14}
}

func (x *ResetPasswordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// --- Get User Data (for service-to-service) ---
type GetUserDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDataRequest) Reset() {
	*x = GetUserDataRequest{}
	mi := &file_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDataRequest) ProtoMessage() {}

func (x *GetUserDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDataRequest.ProtoReflect.Descriptor instead.
func (*GetUserDataRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{15}
}

func (x *GetUserDataRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserDataResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Username          string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	ProfilePictureUrl string                 `protobuf:"bytes,2,opt,name=profile_picture_url,json=profilePictureUrl,proto3" json:"profile_picture_url,omitempty"`
	IsVerified        bool                   `protobuf:"varint,3,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetUserDataResponse) Reset() {
	*x = GetUserDataResponse{}
	mi := &file_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDataResponse) ProtoMessage() {}

func (x *GetUserDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDataResponse.ProtoReflect.Descriptor instead.
func (*GetUserDataResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{16}
}

func (x *GetUserDataResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUserDataResponse) GetProfilePictureUrl() string {
	if x != nil {
		return x.ProfilePictureUrl
	}
	return ""
}

func (x *GetUserDataResponse) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

// --- Follow / Unfollow User ---
type FollowUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    int64                  `protobuf:"varint,1,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`    // The user initiating the follow (from JWT)
	FollowingId   int64                  `protobuf:"varint,2,opt,name=following_id,json=followingId,proto3" json:"following_id,omitempty"` // The user to be followed (from URL)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowUserRequest) Reset() {
	*x = FollowUserRequest{}
	mi := &file_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowUserRequest) ProtoMessage() {}

func (x *FollowUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowUserRequest.ProtoReflect.Descriptor instead.
func (*FollowUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{17}
}

func (x *FollowUserRequest) GetFollowerId() int64 {
	if x != nil {
		return x.FollowerId
	}
	return 0
}

func (x *FollowUserRequest) GetFollowingId() int64 {
	if x != nil {
		return x.FollowingId
	}
	return 0
}

type FollowUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // "Successfully followed user"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowUserResponse) Reset() {
	*x = FollowUserResponse{}
	mi := &file_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowUserResponse) ProtoMessage() {}

func (x *FollowUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowUserResponse.ProtoReflect.Descriptor instead.
func (*FollowUserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{18}
}

func (x *FollowUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UnfollowUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    int64                  `protobuf:"varint,1,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`    // The user initiating the unfollow
	FollowingId   int64                  `protobuf:"varint,2,opt,name=following_id,json=followingId,proto3" json:"following_id,omitempty"` // The user to be unfollowed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowUserRequest) Reset() {
	*x = UnfollowUserRequest{}
	mi := &file_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowUserRequest) ProtoMessage() {}

func (x *UnfollowUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowUserRequest.ProtoReflect.Descriptor instead.
func (*UnfollowUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{19}
}

func (x *UnfollowUserRequest) GetFollowerId() int64 {
	if x != nil {
		return x.FollowerId
	}
	return 0
}

func (x *UnfollowUserRequest) GetFollowingId() int64 {
	if x != nil {
		return x.FollowingId
	}
	return 0
}

type UnfollowUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // "Successfully unfollowed user"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowUserResponse) Reset() {
	*x = UnfollowUserResponse{}
	mi := &file_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowUserResponse) ProtoMessage() {}

func (x *UnfollowUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowUserResponse.ProtoReflect.Descriptor instead.
func (*UnfollowUserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{20}
}

func (x *UnfollowUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// --- Check if Following ---
type IsFollowingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowerId    int64                  `protobuf:"varint,1,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`    // The user who might be following
	FollowingId   int64                  `protobuf:"varint,2,opt,name=following_id,json=followingId,proto3" json:"following_id,omitempty"` // The user to check
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsFollowingRequest) Reset() {
	*x = IsFollowingRequest{}
	mi := &file_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFollowingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFollowingRequest) ProtoMessage() {}

func (x *IsFollowingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFollowingRequest.ProtoReflect.Descriptor instead.
func (*IsFollowingRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{21}
}

func (x *IsFollowingRequest) GetFollowerId() int64 {
	if x != nil {
		return x.FollowerId
	}
	return 0
}

func (x *IsFollowingRequest) GetFollowingId() int64 {
	if x != nil {
		return x.FollowingId
	}
	return 0
}

type IsFollowingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsFollowing   bool                   `protobuf:"varint,1,opt,name=is_following,json=isFollowing,proto3" json:"is_following,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsFollowingResponse) Reset() {
	*x = IsFollowingResponse{}
	mi := &file_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFollowingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFollowingResponse) ProtoMessage() {}

func (x *IsFollowingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFollowingResponse.ProtoReflect.Descriptor instead.
func (*IsFollowingResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{22}
}

func (x *IsFollowingResponse) GetIsFollowing() bool {
	if x != nil {
		return x.IsFollowing
	}
	return false
}

type GetFollowingListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // The user who is asking
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingListRequest) Reset() {
	*x = GetFollowingListRequest{}
	mi := &file_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingListRequest) ProtoMessage() {}

func (x *GetFollowingListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingListRequest.ProtoReflect.Descriptor instead.
func (*GetFollowingListRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{23}
}

func (x *GetFollowingListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetFollowingListResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FollowingUserIds []int64                `protobuf:"varint,1,rep,packed,name=following_user_ids,json=followingUserIds,proto3" json:"following_user_ids,omitempty"` // A list of user IDs
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetFollowingListResponse) Reset() {
	*x = GetFollowingListResponse{}
	mi := &file_user_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingListResponse) ProtoMessage() {}

func (x *GetFollowingListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingListResponse.ProtoReflect.Descriptor instead.
func (*GetFollowingListResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{24}
}

func (x *GetFollowingListResponse) GetFollowingUserIds() []int64 {
	if x != nil {
		return x.FollowingUserIds
	}
	return nil
}

// --- Get User Profile ---
type GetUserProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`                          // The username of the profile we want to view
	SelfUserId    int64                  `protobuf:"varint,2,opt,name=self_user_id,json=selfUserId,proto3" json:"self_user_id,omitempty"` // The ID of the user making the request (from JWT)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileRequest) Reset() {
	*x = GetUserProfileRequest{}
	mi := &file_user_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileRequest) ProtoMessage() {}

func (x *GetUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileRequest.ProtoReflect.Descriptor instead.
func (*GetUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{25}
}

func (x *GetUserProfileRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUserProfileRequest) GetSelfUserId() int64 {
	if x != nil {
		return x.SelfUserId
	}
	return 0
}

type GetUserProfileResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UserId              int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Username            string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Bio                 string                 `protobuf:"bytes,4,opt,name=bio,proto3" json:"bio,omitempty"` // We need to add this to our GORM model
	ProfilePictureUrl   string                 `protobuf:"bytes,5,opt,name=profile_picture_url,json=profilePictureUrl,proto3" json:"profile_picture_url,omitempty"`
	IsVerified          bool                   `protobuf:"varint,6,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	FollowerCount       int64                  `protobuf:"varint,7,opt,name=follower_count,json=followerCount,proto3" json:"follower_count,omitempty"`
	FollowingCount      int64                  `protobuf:"varint,8,opt,name=following_count,json=followingCount,proto3" json:"following_count,omitempty"`
	IsFollowedBySelf    bool                   `protobuf:"varint,9,opt,name=is_followed_by_self,json=isFollowedBySelf,proto3" json:"is_followed_by_self,omitempty"` // Does the person viewing follow this profile?
	MutualFollowerCount int64                  `protobuf:"varint,10,opt,name=mutual_follower_count,json=mutualFollowerCount,proto3" json:"mutual_follower_count,omitempty"`
	Gender              string                 `protobuf:"bytes,11,opt,name=gender,proto3" json:"gender,omitempty"`
	IsPrivate           bool                   `protobuf:"varint,12,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetUserProfileResponse) Reset() {
	*x = GetUserProfileResponse{}
	mi := &file_user_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileResponse) ProtoMessage() {}

func (x *GetUserProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileResponse.ProtoReflect.Descriptor instead.
func (*GetUserProfileResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{26}
}

func (x *GetUserProfileResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserProfileResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetUserProfileResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUserProfileResponse) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *GetUserProfileResponse) GetProfilePictureUrl() string {
	if x != nil {
		return x.ProfilePictureUrl
	}
	return ""
}

func (x *GetUserProfileResponse) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

func (x *GetUserProfileResponse) GetFollowerCount() int64 {
	if x != nil {
		return x.FollowerCount
	}
	return 0
}

func (x *GetUserProfileResponse) GetFollowingCount() int64 {
	if x != nil {
		return x.FollowingCount
	}
	return 0
}

func (x *GetUserProfileResponse) GetIsFollowedBySelf() bool {
	if x != nil {
		return x.IsFollowedBySelf
	}
	return false
}

func (x *GetUserProfileResponse) GetMutualFollowerCount() int64 {
	if x != nil {
		return x.MutualFollowerCount
	}
	return 0
}

func (x *GetUserProfileResponse) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *GetUserProfileResponse) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

// --- Edit User Profile ---
type UpdateUserProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // From JWT
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Bio           string                 `protobuf:"bytes,3,opt,name=bio,proto3" json:"bio,omitempty"`
	Gender        string                 `protobuf:"bytes,4,opt,name=gender,proto3" json:"gender,omitempty"` // We'll add ProfilePictureURL later
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserProfileRequest) Reset() {
	*x = UpdateUserProfileRequest{}
	mi := &file_user_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserProfileRequest) ProtoMessage() {}

func (x *UpdateUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateUserProfileRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserProfileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateUserProfileRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UpdateUserProfileRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

// --- Set Account Privacy ---
type SetAccountPrivacyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // From JWT
	IsPrivate     bool                   `protobuf:"varint,2,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAccountPrivacyRequest) Reset() {
	*x = SetAccountPrivacyRequest{}
	mi := &file_user_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAccountPrivacyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAccountPrivacyRequest) ProtoMessage() {}

func (x *SetAccountPrivacyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAccountPrivacyRequest.ProtoReflect.Descriptor instead.
func (*SetAccountPrivacyRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{28}
}

func (x *SetAccountPrivacyRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SetAccountPrivacyRequest) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

type SetAccountPrivacyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAccountPrivacyResponse) Reset() {
	*x = SetAccountPrivacyResponse{}
	mi := &file_user_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAccountPrivacyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAccountPrivacyResponse) ProtoMessage() {}

func (x *SetAccountPrivacyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAccountPrivacyResponse.ProtoReflect.Descriptor instead.
func (*SetAccountPrivacyResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{29}
}

func (x *SetAccountPrivacyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// --- Block / Unblock User ---
type BlockUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockerId     int64                  `protobuf:"varint,1,opt,name=blocker_id,json=blockerId,proto3" json:"blocker_id,omitempty"` // The user initiating the block (from JWT)
	BlockedId     int64                  `protobuf:"varint,2,opt,name=blocked_id,json=blockedId,proto3" json:"blocked_id,omitempty"` // The user to be blocked (from URL)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockUserRequest) Reset() {
	*x = BlockUserRequest{}
	mi := &file_user_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockUserRequest) ProtoMessage() {}

func (x *BlockUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockUserRequest.ProtoReflect.Descriptor instead.
func (*BlockUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{30}
}

func (x *BlockUserRequest) GetBlockerId() int64 {
	if x != nil {
		return x.BlockerId
	}
	return 0
}

func (x *BlockUserRequest) GetBlockedId() int64 {
	if x != nil {
		return x.BlockedId
	}
	return 0
}

type BlockUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // "Successfully blocked user"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockUserResponse) Reset() {
	*x = BlockUserResponse{}
	mi := &file_user_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockUserResponse) ProtoMessage() {}

func (x *BlockUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockUserResponse.ProtoReflect.Descriptor instead.
func (*BlockUserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{31}
}

func (x *BlockUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UnblockUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockerId     int64                  `protobuf:"varint,1,opt,name=blocker_id,json=blockerId,proto3" json:"blocker_id,omitempty"` // The user initiating the unblock
	BlockedId     int64                  `protobuf:"varint,2,opt,name=blocked_id,json=blockedId,proto3" json:"blocked_id,omitempty"` // The user to be unblocked
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockUserRequest) Reset() {
	*x = UnblockUserRequest{}
	mi := &file_user_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockUserRequest) ProtoMessage() {}

func (x *UnblockUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockUserRequest.ProtoReflect.Descriptor instead.
func (*UnblockUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{32}
}

func (x *UnblockUserRequest) GetBlockerId() int64 {
	if x != nil {
		return x.BlockerId
	}
	return 0
}

func (x *UnblockUserRequest) GetBlockedId() int64 {
	if x != nil {
		return x.BlockedId
	}
	return 0
}

type UnblockUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // "Successfully unblocked user"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockUserResponse) Reset() {
	*x = UnblockUserResponse{}
	mi := &file_user_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockUserResponse) ProtoMessage() {}

func (x *UnblockUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockUserResponse.ProtoReflect.Descriptor instead.
func (*UnblockUserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{33}
}

func (x *UnblockUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// --- Search Users ---
type SearchUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`                                // The search term
	SelfUserId    int64                  `protobuf:"varint,2,opt,name=self_user_id,json=selfUserId,proto3" json:"self_user_id,omitempty"` // From JWT, to exclude self from results
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersRequest) Reset() {
	*x = SearchUsersRequest{}
	mi := &file_user_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersRequest) ProtoMessage() {}

func (x *SearchUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersRequest.ProtoReflect.Descriptor instead.
func (*SearchUsersRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{34}
}

func (x *SearchUsersRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchUsersRequest) GetSelfUserId() int64 {
	if x != nil {
		return x.SelfUserId
	}
	return 0
}

// We can re-use GetUserProfileResponse
type SearchUsersResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Users         []*GetUserProfileResponse `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersResponse) Reset() {
	*x = SearchUsersResponse{}
	mi := &file_user_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersResponse) ProtoMessage() {}

func (x *SearchUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersResponse.ProtoReflect.Descriptor instead.
func (*SearchUsersResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{35}
}

func (x *SearchUsersResponse) GetUsers() []*GetUserProfileResponse {
	if x != nil {
		return x.Users
	}
	return nil
}

// Admin Controls
// --- Admin: Ban / Unban ---
type BanUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminUserId   int64                  `protobuf:"varint,1,opt,name=admin_user_id,json=adminUserId,proto3" json:"admin_user_id,omitempty"`   // From JWT
	UserToBanId   int64                  `protobuf:"varint,2,opt,name=user_to_ban_id,json=userToBanId,proto3" json:"user_to_ban_id,omitempty"` // From URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanUserRequest) Reset() {
	*x = BanUserRequest{}
	mi := &file_user_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanUserRequest) ProtoMessage() {}

func (x *BanUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanUserRequest.ProtoReflect.Descriptor instead.
func (*BanUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{36}
}

func (x *BanUserRequest) GetAdminUserId() int64 {
	if x != nil {
		return x.AdminUserId
	}
	return 0
}

func (x *BanUserRequest) GetUserToBanId() int64 {
	if x != nil {
		return x.UserToBanId
	}
	return 0
}

type BanUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // e.g., "User banned successfully"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanUserResponse) Reset() {
	*x = BanUserResponse{}
	mi := &file_user_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanUserResponse) ProtoMessage() {}

func (x *BanUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanUserResponse.ProtoReflect.Descriptor instead.
func (*BanUserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{37}
}

func (x *BanUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UnbanUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminUserId   int64                  `protobuf:"varint,1,opt,name=admin_user_id,json=adminUserId,proto3" json:"admin_user_id,omitempty"`         // From JWT
	UserToUnbanId int64                  `protobuf:"varint,2,opt,name=user_to_unban_id,json=userToUnbanId,proto3" json:"user_to_unban_id,omitempty"` // From URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbanUserRequest) Reset() {
	*x = UnbanUserRequest{}
	mi := &file_user_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbanUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbanUserRequest) ProtoMessage() {}

func (x *UnbanUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbanUserRequest.ProtoReflect.Descriptor instead.
func (*UnbanUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{38}
}

func (x *UnbanUserRequest) GetAdminUserId() int64 {
	if x != nil {
		return x.AdminUserId
	}
	return 0
}

func (x *UnbanUserRequest) GetUserToUnbanId() int64 {
	if x != nil {
		return x.UserToUnbanId
	}
	return 0
}

type UnbanUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // e.g., "User unbanned successfully"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbanUserResponse) Reset() {
	*x = UnbanUserResponse{}
	mi := &file_user_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbanUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbanUserResponse) ProtoMessage() {}

func (x *UnbanUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbanUserResponse.ProtoReflect.Descriptor instead.
func (*UnbanUserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{39}
}

func (x *UnbanUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// --- Admin: Newsletter ---
type SendNewsletterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminUserId   int64                  `protobuf:"varint,1,opt,name=admin_user_id,json=adminUserId,proto3" json:"admin_user_id,omitempty"` // From JWT
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNewsletterRequest) Reset() {
	*x = SendNewsletterRequest{}
	mi := &file_user_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNewsletterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNewsletterRequest) ProtoMessage() {}

func (x *SendNewsletterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNewsletterRequest.ProtoReflect.Descriptor instead.
func (*SendNewsletterRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{40}
}

func (x *SendNewsletterRequest) GetAdminUserId() int64 {
	if x != nil {
		return x.AdminUserId
	}
	return 0
}

func (x *SendNewsletterRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendNewsletterRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type SendNewsletterResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Message         string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	RecipientsCount int32                  `protobuf:"varint,2,opt,name=recipients_count,json=recipientsCount,proto3" json:"recipients_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SendNewsletterResponse) Reset() {
	*x = SendNewsletterResponse{}
	mi := &file_user_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNewsletterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNewsletterResponse) ProtoMessage() {}

func (x *SendNewsletterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNewsletterResponse.ProtoReflect.Descriptor instead.
func (*SendNewsletterResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{41}
}

func (x *SendNewsletterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendNewsletterResponse) GetRecipientsCount() int32 {
	if x != nil {
		return x.RecipientsCount
	}
	return 0
}

// --- User: Submit Verification ---
type VerificationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IdCardNumber   string                 `protobuf:"bytes,3,opt,name=id_card_number,json=idCardNumber,proto3" json:"id_card_number,omitempty"`
	FacePictureUrl string                 `protobuf:"bytes,4,opt,name=face_picture_url,json=facePictureUrl,proto3" json:"face_picture_url,omitempty"`
	Reason         string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Username       string                 `protobuf:"bytes,8,opt,name=username,proto3" json:"username,omitempty"` // Denormalized
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VerificationRequest) Reset() {
	*x = VerificationRequest{}
	mi := &file_user_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationRequest) ProtoMessage() {}

func (x *VerificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationRequest.ProtoReflect.Descriptor instead.
func (*VerificationRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{42}
}

func (x *VerificationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VerificationRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *VerificationRequest) GetIdCardNumber() string {
	if x != nil {
		return x.IdCardNumber
	}
	return ""
}

func (x *VerificationRequest) GetFacePictureUrl() string {
	if x != nil {
		return x.FacePictureUrl
	}
	return ""
}

func (x *VerificationRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *VerificationRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *VerificationRequest) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *VerificationRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type SubmitVerificationRequestRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // From JWT
	IdCardNumber   string                 `protobuf:"bytes,2,opt,name=id_card_number,json=idCardNumber,proto3" json:"id_card_number,omitempty"`
	FacePictureUrl string                 `protobuf:"bytes,3,opt,name=face_picture_url,json=facePictureUrl,proto3" json:"face_picture_url,omitempty"`
	Reason         string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubmitVerificationRequestRequest) Reset() {
	*x = SubmitVerificationRequestRequest{}
	mi := &file_user_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitVerificationRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitVerificationRequestRequest) ProtoMessage() {}

func (x *SubmitVerificationRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitVerificationRequestRequest.ProtoReflect.Descriptor instead.
func (*SubmitVerificationRequestRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{43}
}

func (x *SubmitVerificationRequestRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SubmitVerificationRequestRequest) GetIdCardNumber() string {
	if x != nil {
		return x.IdCardNumber
	}
	return ""
}

func (x *SubmitVerificationRequestRequest) GetFacePictureUrl() string {
	if x != nil {
		return x.FacePictureUrl
	}
	return ""
}

func (x *SubmitVerificationRequestRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type SubmitVerificationRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *VerificationRequest   `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitVerificationRequestResponse) Reset() {
	*x = SubmitVerificationRequestResponse{}
	mi := &file_user_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitVerificationRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitVerificationRequestResponse) ProtoMessage() {}

func (x *SubmitVerificationRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitVerificationRequestResponse.ProtoReflect.Descriptor instead.
func (*SubmitVerificationRequestResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{44}
}

func (x *SubmitVerificationRequestResponse) GetRequest() *VerificationRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

// --- Admin: Manage Verifications ---
type GetVerificationRequestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageOffset    int32                  `protobuf:"varint,2,opt,name=page_offset,json=pageOffset,proto3" json:"page_offset,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // "pending", "approved", "rejected"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVerificationRequestsRequest) Reset() {
	*x = GetVerificationRequestsRequest{}
	mi := &file_user_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVerificationRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVerificationRequestsRequest) ProtoMessage() {}

func (x *GetVerificationRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVerificationRequestsRequest.ProtoReflect.Descriptor instead.
func (*GetVerificationRequestsRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{45}
}

func (x *GetVerificationRequestsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetVerificationRequestsRequest) GetPageOffset() int32 {
	if x != nil {
		return x.PageOffset
	}
	return 0
}

func (x *GetVerificationRequestsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetVerificationRequestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*VerificationRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVerificationRequestsResponse) Reset() {
	*x = GetVerificationRequestsResponse{}
	mi := &file_user_proto_msgTypes[46]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVerificationRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVerificationRequestsResponse) ProtoMessage() {}

func (x *GetVerificationRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[46]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVerificationRequestsResponse.ProtoReflect.Descriptor instead.
func (*GetVerificationRequestsResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{46}
}

func (x *GetVerificationRequestsResponse) GetRequests() []*VerificationRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type ResolveVerificationRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminUserId   int64                  `protobuf:"varint,1,opt,name=admin_user_id,json=adminUserId,proto3" json:"admin_user_id,omitempty"` // From JWT
	RequestId     int64                  `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"` // "APPROVE" or "REJECT"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveVerificationRequestRequest) Reset() {
	*x = ResolveVerificationRequestRequest{}
	mi := &file_user_proto_msgTypes[47]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveVerificationRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveVerificationRequestRequest) ProtoMessage() {}

func (x *ResolveVerificationRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[47]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveVerificationRequestRequest.ProtoReflect.Descriptor instead.
func (*ResolveVerificationRequestRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{47}
}

func (x *ResolveVerificationRequestRequest) GetAdminUserId() int64 {
	if x != nil {
		return x.AdminUserId
	}
	return 0
}

func (x *ResolveVerificationRequestRequest) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *ResolveVerificationRequestRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type ResolveVerificationRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveVerificationRequestResponse) Reset() {
	*x = ResolveVerificationRequestResponse{}
	mi := &file_user_proto_msgTypes[48]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveVerificationRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveVerificationRequestResponse) ProtoMessage() {}

func (x *ResolveVerificationRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[48]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveVerificationRequestResponse.ProtoReflect.Descriptor instead.
func (*ResolveVerificationRequestResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{48}
}

func (x *ResolveVerificationRequestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04user\"\xde\x01\n" +
	"\x13RegisterUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\"\n" +
	"\rdate_of_birth\x18\x05 \x01(\tR\vdateOfBirth\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\tR\x06gender\x12)\n" +
	"\x10confirm_password\x18\t \x01(\tR\x0fconfirmPassword\"r\n" +
	"\x14RegisterUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"&\n" +
	"\x0eSendOtpRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"Y\n" +
	"\x0fSendOtpResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12,\n" +
	"\x12rate_limit_seconds\x18\x02 \x01(\x05R\x10rateLimitSeconds\"6\n" +
	"\x17HandleGoogleAuthRequest\x12\x1b\n" +
	"\tauth_code\x18\x01 \x01(\tR\bauthCode\"O\n" +
	"\x1cVerifyRegistrationOtpRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x19\n" +
	"\botp_code\x18\x02 \x01(\tR\aotpCode\"g\n" +
	"\x1dVerifyRegistrationOtpResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"V\n" +
	"\fLoginRequest\x12*\n" +
	"\x11email_or_username\x18\x01 \x01(\tR\x0femailOrUsername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x99\x01\n" +
	"\rLoginResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12&\n" +
	"\x0fis_2fa_required\x18\x04 \x01(\bR\ris2faRequired\"C\n" +
	"\x10Verify2FARequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x19\n" +
	"\botp_code\x18\x02 \x01(\tR\aotpCode\"[\n" +
	"\x11Verify2FAResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"0\n" +
	"\x18SendPasswordResetRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"5\n" +
	"\x19SendPasswordResetResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"j\n" +
	"\x14ResetPasswordRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x19\n" +
	"\botp_code\x18\x02 \x01(\tR\aotpCode\x12!\n" +
	"\fnew_password\x18\x03 \x01(\tR\vnewPassword\"1\n" +
	"\x15ResetPasswordResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"-\n" +
	"\x12GetUserDataRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\x82\x01\n" +
	"\x13GetUserDataResponse\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12.\n" +
	"\x13profile_picture_url\x18\x02 \x01(\tR\x11profilePictureUrl\x12\x1f\n" +
	"\vis_verified\x18\x03 \x01(\bR\n" +
	"isVerified\"W\n" +
	"\x11FollowUserRequest\x12\x1f\n" +
	"\vfollower_id\x18\x01 \x01(\x03R\n" +
	"followerId\x12!\n" +
	"\ffollowing_id\x18\x02 \x01(\x03R\vfollowingId\".\n" +
	"\x12FollowUserResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"Y\n" +
	"\x13UnfollowUserRequest\x12\x1f\n" +
	"\vfollower_id\x18\x01 \x01(\x03R\n" +
	"followerId\x12!\n" +
	"\ffollowing_id\x18\x02 \x01(\x03R\vfollowingId\"0\n" +
	"\x14UnfollowUserResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"X\n" +
	"\x12IsFollowingRequest\x12\x1f\n" +
	"\vfollower_id\x18\x01 \x01(\x03R\n" +
	"followerId\x12!\n" +
	"\ffollowing_id\x18\x02 \x01(\x03R\vfollowingId\"8\n" +
	"\x13IsFollowingResponse\x12!\n" +
	"\fis_following\x18\x01 \x01(\bR\visFollowing\"2\n" +
	"\x17GetFollowingListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"H\n" +
	"\x18GetFollowingListResponse\x12,\n" +
	"\x12following_user_ids\x18\x01 \x03(\x03R\x10followingUserIds\"U\n" +
	"\x15GetUserProfileRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12 \n" +
	"\fself_user_id\x18\x02 \x01(\x03R\n" +
	"selfUserId\"\xae\x03\n" +
	"\x16GetUserProfileResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x10\n" +
	"\x03bio\x18\x04 \x01(\tR\x03bio\x12.\n" +
	"\x13profile_picture_url\x18\x05 \x01(\tR\x11profilePictureUrl\x12\x1f\n" +
	"\vis_verified\x18\x06 \x01(\bR\n" +
	"isVerified\x12%\n" +
	"\x0efollower_count\x18\a \x01(\x03R\rfollowerCount\x12'\n" +
	"\x0ffollowing_count\x18\b \x01(\x03R\x0efollowingCount\x12-\n" +
	"\x13is_followed_by_self\x18\t \x01(\bR\x10isFollowedBySelf\x122\n" +
	"\x15mutual_follower_count\x18\n" +
	" \x01(\x03R\x13mutualFollowerCount\x12\x16\n" +
	"\x06gender\x18\v \x01(\tR\x06gender\x12\x1d\n" +
	"\n" +
	"is_private\x18\f \x01(\bR\tisPrivate\"q\n" +
	"\x18UpdateUserProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03bio\x18\x03 \x01(\tR\x03bio\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\tR\x06gender\"R\n" +
	"\x18SetAccountPrivacyRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"is_private\x18\x02 \x01(\bR\tisPrivate\"5\n" +
	"\x19SetAccountPrivacyResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"P\n" +
	"\x10BlockUserRequest\x12\x1d\n" +
	"\n" +
	"blocker_id\x18\x01 \x01(\x03R\tblockerId\x12\x1d\n" +
	"\n" +
	"blocked_id\x18\x02 \x01(\x03R\tblockedId\"-\n" +
	"\x11BlockUserResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"R\n" +
	"\x12UnblockUserRequest\x12\x1d\n" +
	"\n" +
	"blocker_id\x18\x01 \x01(\x03R\tblockerId\x12\x1d\n" +
	"\n" +
	"blocked_id\x18\x02 \x01(\x03R\tblockedId\"/\n" +
	"\x13UnblockUserResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"L\n" +
	"\x12SearchUsersRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12 \n" +
	"\fself_user_id\x18\x02 \x01(\x03R\n" +
	"selfUserId\"I\n" +
	"\x13SearchUsersResponse\x122\n" +
	"\x05users\x18\x01 \x03(\v2\x1c.user.GetUserProfileResponseR\x05users\"Y\n" +
	"\x0eBanUserRequest\x12\"\n" +
	"\radmin_user_id\x18\x01 \x01(\x03R\vadminUserId\x12#\n" +
	"\x0euser_to_ban_id\x18\x02 \x01(\x03R\vuserToBanId\"+\n" +
	"\x0fBanUserResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"_\n" +
	"\x10UnbanUserRequest\x12\"\n" +
	"\radmin_user_id\x18\x01 \x01(\x03R\vadminUserId\x12'\n" +
	"\x10user_to_unban_id\x18\x02 \x01(\x03R\ruserToUnbanId\"-\n" +
	"\x11UnbanUserResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"i\n" +
	"\x15SendNewsletterRequest\x12\"\n" +
	"\radmin_user_id\x18\x01 \x01(\x03R\vadminUserId\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\"]\n" +
	"\x16SendNewsletterResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12)\n" +
	"\x10recipients_count\x18\x02 \x01(\x05R\x0frecipientsCount\"\xf9\x01\n" +
	"\x13VerificationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12$\n" +
	"\x0eid_card_number\x18\x03 \x01(\tR\fidCardNumber\x12(\n" +
	"\x10face_picture_url\x18\x04 \x01(\tR\x0efacePictureUrl\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1a\n" +
	"\busername\x18\b \x01(\tR\busername\"\xa3\x01\n" +
	" SubmitVerificationRequestRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12$\n" +
	"\x0eid_card_number\x18\x02 \x01(\tR\fidCardNumber\x12(\n" +
	"\x10face_picture_url\x18\x03 \x01(\tR\x0efacePictureUrl\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"X\n" +
	"!SubmitVerificationRequestResponse\x123\n" +
	"\arequest\x18\x01 \x01(\v2\x19.user.VerificationRequestR\arequest\"v\n" +
	"\x1eGetVerificationRequestsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vpage_offset\x18\x02 \x01(\x05R\n" +
	"pageOffset\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"X\n" +
	"\x1fGetVerificationRequestsResponse\x125\n" +
	"\brequests\x18\x01 \x03(\v2\x19.user.VerificationRequestR\brequests\"~\n" +
	"!ResolveVerificationRequestRequest\x12\"\n" +
	"\radmin_user_id\x18\x01 \x01(\x03R\vadminUserId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\x03R\trequestId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\">\n" +
	"\"ResolveVerificationRequestResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xff\x0e\n" +
	"\vUserService\x12E\n" +
	"\fRegisterUser\x12\x19.user.RegisterUserRequest\x1a\x1a.user.RegisterUserResponse\x12B\n" +
	"\x13SendRegistrationOtp\x12\x14.user.SendOtpRequest\x1a\x15.user.SendOtpResponse\x12`\n" +
	"\x15VerifyRegistrationOtp\x12\".user.VerifyRegistrationOtpRequest\x1a#.user.VerifyRegistrationOtpResponse\x124\n" +
	"\tLoginUser\x12\x12.user.LoginRequest\x1a\x13.user.LoginResponse\x12<\n" +
	"\tVerify2FA\x12\x16.user.Verify2FARequest\x1a\x17.user.Verify2FAResponse\x12T\n" +
	"\x11SendPasswordReset\x12\x1e.user.SendPasswordResetRequest\x1a\x1f.user.SendPasswordResetResponse\x12H\n" +
	"\rResetPassword\x12\x1a.user.ResetPasswordRequest\x1a\x1b.user.ResetPasswordResponse\x12B\n" +
	"\vGetUserData\x12\x18.user.GetUserDataRequest\x1a\x19.user.GetUserDataResponse\x12?\n" +
	"\n" +
	"FollowUser\x12\x17.user.FollowUserRequest\x1a\x18.user.FollowUserResponse\x12E\n" +
	"\fUnfollowUser\x12\x19.user.UnfollowUserRequest\x1a\x1a.user.UnfollowUserResponse\x12B\n" +
	"\vIsFollowing\x12\x18.user.IsFollowingRequest\x1a\x19.user.IsFollowingResponse\x12Q\n" +
	"\x10GetFollowingList\x12\x1d.user.GetFollowingListRequest\x1a\x1e.user.GetFollowingListResponse\x12K\n" +
	"\x0eGetUserProfile\x12\x1b.user.GetUserProfileRequest\x1a\x1c.user.GetUserProfileResponse\x12Q\n" +
	"\x11UpdateUserProfile\x12\x1e.user.UpdateUserProfileRequest\x1a\x1c.user.GetUserProfileResponse\x12T\n" +
	"\x11SetAccountPrivacy\x12\x1e.user.SetAccountPrivacyRequest\x1a\x1f.user.SetAccountPrivacyResponse\x12<\n" +
	"\tBlockUser\x12\x16.user.BlockUserRequest\x1a\x17.user.BlockUserResponse\x12B\n" +
	"\vUnblockUser\x12\x18.user.UnblockUserRequest\x1a\x19.user.UnblockUserResponse\x12B\n" +
	"\vSearchUsers\x12\x18.user.SearchUsersRequest\x1a\x19.user.SearchUsersResponse\x126\n" +
	"\aBanUser\x12\x14.user.BanUserRequest\x1a\x15.user.BanUserResponse\x12<\n" +
	"\tUnbanUser\x12\x16.user.UnbanUserRequest\x1a\x17.user.UnbanUserResponse\x12K\n" +
	"\x0eSendNewsletter\x12\x1b.user.SendNewsletterRequest\x1a\x1c.user.SendNewsletterResponse\x12l\n" +
	"\x19SubmitVerificationRequest\x12&.user.SubmitVerificationRequestRequest\x1a'.user.SubmitVerificationRequestResponse\x12f\n" +
	"\x17GetVerificationRequests\x12$.user.GetVerificationRequestsRequest\x1a%.user.GetVerificationRequestsResponse\x12o\n" +
	"\x1aResolveVerificationRequest\x12'.user.ResolveVerificationRequestRequest\x1a(.user.ResolveVerificationRequestResponse\x12F\n" +
	"\x10HandleGoogleAuth\x12\x1d.user.HandleGoogleAuthRequest\x1a\x13.user.LoginResponseB,Z*github.com/hoshibmatchi/user-service/protob\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 49)
var file_user_proto_goTypes = []any{
	(*RegisterUserRequest)(nil),                // 0: user.RegisterUserRequest
	(*RegisterUserResponse)(nil),               // 1: user.RegisterUserResponse
	(*SendOtpRequest)(nil),                     // 2: user.SendOtpRequest
	(*SendOtpResponse)(nil),                    // 3: user.SendOtpResponse
	(*HandleGoogleAuthRequest)(nil),            // 4: user.HandleGoogleAuthRequest
	(*VerifyRegistrationOtpRequest)(nil),       // 5: user.VerifyRegistrationOtpRequest
	(*VerifyRegistrationOtpResponse)(nil),      // 6: user.VerifyRegistrationOtpResponse
	(*LoginRequest)(nil),                       // 7: user.LoginRequest
	(*LoginResponse)(nil),                      // 8: user.LoginResponse
	(*Verify2FARequest)(nil),                   // 9: user.Verify2FARequest
	(*Verify2FAResponse)(nil),                  // 10: user.Verify2FAResponse
	(*SendPasswordResetRequest)(nil),           // 11: user.SendPasswordResetRequest
	(*SendPasswordResetResponse)(nil),          // 12: user.SendPasswordResetResponse
	(*ResetPasswordRequest)(nil),               // 13: user.ResetPasswordRequest
	(*ResetPasswordResponse)(nil),              // 14: user.ResetPasswordResponse
	(*GetUserDataRequest)(nil),                 // 15: user.GetUserDataRequest
	(*GetUserDataResponse)(nil),                // 16: user.GetUserDataResponse
	(*FollowUserRequest)(nil),                  // 17: user.FollowUserRequest
	(*FollowUserResponse)(nil),                 // 18: user.FollowUserResponse
	(*UnfollowUserRequest)(nil),                // 19: user.UnfollowUserRequest
	(*UnfollowUserResponse)(nil),               // 20: user.UnfollowUserResponse
	(*IsFollowingRequest)(nil),                 // 21: user.IsFollowingRequest
	(*IsFollowingResponse)(nil),                // 22: user.IsFollowingResponse
	(*GetFollowingListRequest)(nil),            // 23: user.GetFollowingListRequest
	(*GetFollowingListResponse)(nil),           // 24: user.GetFollowingListResponse
	(*GetUserProfileRequest)(nil),              // 25: user.GetUserProfileRequest
	(*GetUserProfileResponse)(nil),             // 26: user.GetUserProfileResponse
	(*UpdateUserProfileRequest)(nil),           // 27: user.UpdateUserProfileRequest
	(*SetAccountPrivacyRequest)(nil),           // 28: user.SetAccountPrivacyRequest
	(*SetAccountPrivacyResponse)(nil),          // 29: user.SetAccountPrivacyResponse
	(*BlockUserRequest)(nil),                   // 30: user.BlockUserRequest
	(*BlockUserResponse)(nil),                  // 31: user.BlockUserResponse
	(*UnblockUserRequest)(nil),                 // 32: user.UnblockUserRequest
	(*UnblockUserResponse)(nil),                // 33: user.UnblockUserResponse
	(*SearchUsersRequest)(nil),                 // 34: user.SearchUsersRequest
	(*SearchUsersResponse)(nil),                // 35: user.SearchUsersResponse
	(*BanUserRequest)(nil),                     // 36: user.BanUserRequest
	(*BanUserResponse)(nil),                    // 37: user.BanUserResponse
	(*UnbanUserRequest)(nil),                   // 38: user.UnbanUserRequest
	(*UnbanUserResponse)(nil),                  // 39: user.UnbanUserResponse
	(*SendNewsletterRequest)(nil),              // 40: user.SendNewsletterRequest
	(*SendNewsletterResponse)(nil),             // 41: user.SendNewsletterResponse
	(*VerificationRequest)(nil),                // 42: user.VerificationRequest
	(*SubmitVerificationRequestRequest)(nil),   // 43: user.SubmitVerificationRequestRequest
	(*SubmitVerificationRequestResponse)(nil),  // 44: user.SubmitVerificationRequestResponse
	(*GetVerificationRequestsRequest)(nil),     // 45: user.GetVerificationRequestsRequest
	(*GetVerificationRequestsResponse)(nil),    // 46: user.GetVerificationRequestsResponse
	(*ResolveVerificationRequestRequest)(nil),  // 47: user.ResolveVerificationRequestRequest
	(*ResolveVerificationRequestResponse)(nil), // 48: user.ResolveVerificationRequestResponse
}
var file_user_proto_depIdxs = []int32{
	26, // 0: user.SearchUsersResponse.users:type_name -> user.GetUserProfileResponse
	42, // 1: user.SubmitVerificationRequestResponse.request:type_name -> user.VerificationRequest
	42, // 2: user.GetVerificationRequestsResponse.requests:type_name -> user.VerificationRequest
	0,  // 3: user.UserService.RegisterUser:input_type -> user.RegisterUserRequest
	2,  // 4: user.UserService.SendRegistrationOtp:input_type -> user.SendOtpRequest
	5,  // 5: user.UserService.VerifyRegistrationOtp:input_type -> user.VerifyRegistrationOtpRequest
	7,  // 6: user.UserService.LoginUser:input_type -> user.LoginRequest
	9,  // 7: user.UserService.Verify2FA:input_type -> user.Verify2FARequest
	11, // 8: user.UserService.SendPasswordReset:input_type -> user.SendPasswordResetRequest
	13, // 9: user.UserService.ResetPassword:input_type -> user.ResetPasswordRequest
	15, // 10: user.UserService.GetUserData:input_type -> user.GetUserDataRequest
	17, // 11: user.UserService.FollowUser:input_type -> user.FollowUserRequest
	19, // 12: user.UserService.UnfollowUser:input_type -> user.UnfollowUserRequest
	21, // 13: user.UserService.IsFollowing:input_type -> user.IsFollowingRequest
	23, // 14: user.UserService.GetFollowingList:input_type -> user.GetFollowingListRequest
	25, // 15: user.UserService.GetUserProfile:input_type -> user.GetUserProfileRequest
	27, // 16: user.UserService.UpdateUserProfile:input_type -> user.UpdateUserProfileRequest
	28, // 17: user.UserService.SetAccountPrivacy:input_type -> user.SetAccountPrivacyRequest
	30, // 18: user.UserService.BlockUser:input_type -> user.BlockUserRequest
	32, // 19: user.UserService.UnblockUser:input_type -> user.UnblockUserRequest
	34, // 20: user.UserService.SearchUsers:input_type -> user.SearchUsersRequest
	36, // 21: user.UserService.BanUser:input_type -> user.BanUserRequest
	38, // 22: user.UserService.UnbanUser:input_type -> user.UnbanUserRequest
	40, // 23: user.UserService.SendNewsletter:input_type -> user.SendNewsletterRequest
	43, // 24: user.UserService.SubmitVerificationRequest:input_type -> user.SubmitVerificationRequestRequest
	45, // 25: user.UserService.GetVerificationRequests:input_type -> user.GetVerificationRequestsRequest
	47, // 26: user.UserService.ResolveVerificationRequest:input_type -> user.ResolveVerificationRequestRequest
	4,  // 27: user.UserService.HandleGoogleAuth:input_type -> user.HandleGoogleAuthRequest
	1,  // 28: user.UserService.RegisterUser:output_type -> user.RegisterUserResponse
	3,  // 29: user.UserService.SendRegistrationOtp:output_type -> user.SendOtpResponse
	6,  // 30: user.UserService.VerifyRegistrationOtp:output_type -> user.VerifyRegistrationOtpResponse
	8,  // 31: user.UserService.LoginUser:output_type -> user.LoginResponse
	10, // 32: user.UserService.Verify2FA:output_type -> user.Verify2FAResponse
	12, // 33: user.UserService.SendPasswordReset:output_type -> user.SendPasswordResetResponse
	14, // 34: user.UserService.ResetPassword:output_type -> user.ResetPasswordResponse
	16, // 35: user.UserService.GetUserData:output_type -> user.GetUserDataResponse
	18, // 36: user.UserService.FollowUser:output_type -> user.FollowUserResponse
	20, // 37: user.UserService.UnfollowUser:output_type -> user.UnfollowUserResponse
	22, // 38: user.UserService.IsFollowing:output_type -> user.IsFollowingResponse
	24, // 39: user.UserService.GetFollowingList:output_type -> user.GetFollowingListResponse
	26, // 40: user.UserService.GetUserProfile:output_type -> user.GetUserProfileResponse
	26, // 41: user.UserService.UpdateUserProfile:output_type -> user.GetUserProfileResponse
	29, // 42: user.UserService.SetAccountPrivacy:output_type -> user.SetAccountPrivacyResponse
	31, // 43: user.UserService.BlockUser:output_type -> user.BlockUserResponse
	33, // 44: user.UserService.UnblockUser:output_type -> user.UnblockUserResponse
	35, // 45: user.UserService.SearchUsers:output_type -> user.SearchUsersResponse
	37, // 46: user.UserService.BanUser:output_type -> user.BanUserResponse
	39, // 47: user.UserService.UnbanUser:output_type -> user.UnbanUserResponse
	41, // 48: user.UserService.SendNewsletter:output_type -> user.SendNewsletterResponse
	44, // 49: user.UserService.SubmitVerificationRequest:output_type -> user.SubmitVerificationRequestResponse
	46, // 50: user.UserService.GetVerificationRequests:output_type -> user.GetVerificationRequestsResponse
	48, // 51: user.UserService.ResolveVerificationRequest:output_type -> user.ResolveVerificationRequestResponse
	8,  // 52: user.UserService.HandleGoogleAuth:output_type -> user.LoginResponse
	28, // [28:53] is the sub-list for method output_type
	3,  // [3:28] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   49,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
